name: 'bolt_blueprint'
version: '1.0.0'
config-version: 2

profile: 'bolt_blueprint'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: [
    "macros",
    "dbt_packages/bolt_dbt_utils/macros"
]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
    # General vars
    week_start: 'Monday' # Abbreviation and full name both work
    currency: "USD"

    # Googleads vars
    googleads_conversion_used_by_custom_conversions: 'all_conversions'   # Googleads custom conversions can use conversions or all_conversions

    # Shopify vars
    time_zone: 'US/Eastern'
    order_tags_keyword_exclusion: 'dummy' # exclude orders with tags including certain keywords from analytics e.g. 'dummy1|dummy2'
    sales_channel_exclusion: 'dummy' # exclude orders that came from certain sales channels from analytics e.g. 'channel1|channel2'

models:
  bolt_blueprint:
    base:
      +schema: base
      +materialized: table
      
    reporting:
      +schema: reporting
      +materialized: table
